### PR TITLE
WIP Persisted state

### PR DESCRIPTION
**Pull request by Grawl**
Save part of store to Local Storage

### CODE REVIEW

**Comment by Grawl** [comment]
Not working yet.

**Comment by Grawl** [comment]
Just tried also [`pinia-plugin-persist`](https://github.com/Seb-L/pinia-plugin-persist) instead of [`pinia-plugin-persistedstate`](https://github.com/prazdevs/pinia-plugin-persistedstate) but with no luck

**Comment by TobyMosque** [comment]
I pushed a example with persistence:

https://github.com/TobyMosque/quasar-v2-ssr-pinia/blob/master/src/boot/persist-store.ts
https://github.com/TobyMosque/quasar-v2-ssr-pinia/blob/master/src/pages/Index.vue#L26

**Comment by Grawl** [comment]
I checked it and it working. Thank you.

**Comment by Grawl** [comment]
But how about partial store persisting? Like this:

```ts
const usePersistedSessionStorage = defineStore('persisted-SessionStorage', {
  state: () => ({
    id: '',
    list: [],
  }),
  persist: {
    storage: SessionStorage,
    paths: ['id'],
  }
});
```

**Pull request closed without merging**
